apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2  # Số lượng Pod sẽ được tạo
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Sử dụng image Nginx chính thức
        ports:
        - containerPort: 80  # Nginx lắng nghe cổng 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # Cổng của Service
      targetPort: 80  # Cổng của Pod
  type: NodePort  # Loại Service cho phép truy cập từ bên ngoài
